import Header from '@/components/Header';
import styles from '@/styles/Home.module.css';
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ fichesVertes }) {
   //  console.log(('fichesVertes', fichesVertes));
   return (
      <>
         <Head>
            <title>Fiches vertes LASERPHOT</title>
            <meta name='description' content='Generated by create next app' />
            <meta
               name='viewport'
               content='width=device-width, initial-scale=1'
            />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <Header />

         <main className={`${styles.main}`}>
            <div className={styles.grid}>
               {fichesVertes.map((ficheVerte) => {
                  return (
                     // eslint-disable-next-line react/jsx-key
                     <a key={ficheVerte.id} className={styles.card}>
                        <p>
                           <strong>Date : </strong>
                           {new Date(ficheVerte.createdAt).toLocaleDateString(
                              'fr-FR'
                           )}
                        </p>
                        <h4>{ficheVerte.LAS}</h4>
                        <h4>OF : {ficheVerte.OF}</h4>
                        <p>
                           <strong>Client : </strong>
                           {ficheVerte.CLIENT}
                        </p>
                        {/* <p>
                           <strong>Nombre d'amalgames : </strong>
                           {ficheVerte.AMALGAME}
                        </p> */}
                        <p>
                           <strong>Nouveau / Modif : </strong>
                           {ficheVerte.nouveaux}
                        </p>
                        <p>
                           <strong>Retirage : </strong>
                           {ficheVerte.retirage}
                        </p>
                        <p>
                           <strong>Ozalid(s) : </strong>
                           {ficheVerte.ozalid}
                        </p>
                        <p>
                           <strong>GMG(S) : </strong>
                           {ficheVerte.gmg}
                        </p>
                        <p>
                           <strong>TOTAL : </strong>
                           {ficheVerte.total} €
                        </p>
                     </a>
                  );
               })}
            </div>
         </main>
      </>
   );
}

export async function getStaticProps() {
   const client = new ApolloClient({
      uri: 'https://fiches-vertes-api.vercel.app/api/graphql',
      cache: new InMemoryCache(),
   });

   const { data } = await client.query({
      query: gql`
         query FicheVerte {
            getFicheVerte {
               LAS
               CLIENT
               OF
               AMALGAME
               retirage
               nouveaux
               ozalid
               gmg
               total
               createdAt
            }
         }
      `,
   });

   //  console.log('data', data);

   return {
      props: {
         fichesVertes: data.getFicheVerte,
      },
   };
}
